<?php

$track = $this->request->getQuery('track');
$playlist =  $this->session->playlist;
?>

<form action="/spotify/playlistadd" method="post">
    <select name="playlist" id="">
        <?php foreach ($playlist as $key => $val) { ?>
            <option value="<?php echo $val->id ?>"><?php echo $val->name ?></option>
        <?php } ?> 
    </select>
    <input type="hidden" name="trackid" value="<?php echo $track?>">
    <input type="submit" value="Add to playlist">
</form>