<?php

?>
<?php echo $this->tag->form("spotify/search"); ?>
    
        <p>
            <label for="name"></label>
            <?php echo $this->tag->textField("name"); ?>
        </p>
        <p>
            <input type="hidden" name="token" value="<?php echo $result['access_token'] ?>">
        </p>
        <p>
            <input type="checkbox" name="filter[]" id="" value="album">Album
            <input type="checkbox" name="filter[]" id="" value="artist">Artist
            <input type="checkbox" name="filter[]" id="" value="playlist">Playlist
            <input type="checkbox" name="filter[]" id="" value="track">Track
            <input type="checkbox" name="filter[]" id="" value="show">Show
            <input type="checkbox" name="filter[]" id="" value="episode">Episode

        </p>
        <p>
            <?php echo $this->tag->submitButton(["Search", 'name'=>'searchbtn']); ?>
        </p>
    
    </form>

    <div class="recommendation">
  <?php

  echo '<pre>';
  $data = $recomendation->tracks;
  ?>
</div>

<h1 class="text-center my-5">Recommendation</h1>
<div class="row w-75 m-auto">

<?php foreach ($data as $key => $val) {
?>
  <div class="card col-sm-3 col-md-3" style="width: 18rem;">
    <img class="card-img-top" src="<?php echo $val->album->images[0]->url; ?>" width="100px" height="200px" alt="Card image cap">
    <div class="card-body">
      <h3><?php echo $val->album->name; ?></h3>          
    </div>
  </div>
<?php } ?>

</div>
    