

<a href="index/login" class="btn btn-primary">Login</a>
<h2>Sign up using this form</h2>

<?php echo $this->tag->form("index/signup"); ?>

    <p>
        <label for="name">Name: </label>
        <?php echo $this->tag->textField("name"); ?>
    </p>
    <p>
        <label for="email">E-Mail: </label>
        <?php echo $this->tag->textField("email"); ?>
    </p>
    <p>
        <label for="username">Username: </label>
        <?php echo $this->tag->textField("username"); ?>
    </p>
    <p>
        <label for="password">Password: </label>
        <?php echo $this->tag->passwordField("password"); ?>
    </p>
    <p>
        <?php echo $this->tag->submitButton("Signup"); ?><br>
    </p>
</form>

